pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "turfnow-app"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          docker.build("${DOCKER_IMAGE}")
        }
      }
    }

    stage('Push Image to Registry') {
      steps {
        echo 'Pushing Docker image to registry...'
      }
    }

    stage('Deploy to EKS') {
      steps {
        echo 'Running kubectl apply to deploy app...'
      }
    }
  }
}
